AutoScalingRole:
  Type: AWS::IAM::Role
  Properties:
    RoleName: !Sub "${AppName}-${Environment}-autoscaling-role"
    ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceAutoscaleRole
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Principal:
            Service: application-autoscaling.amazonaws.com
          Action: sts:AssumeRole

ScalableTarget:
  Type: AWS::ApplicationAutoScaling::ScalableTarget
  DependsOn: EcsService
  Properties:
    ServiceNamespace: ecs
    ResourceId: !Sub "service/${AppName}-${Environment}-cluster/${AppName}-${Environment}-service"
    ScalableDimension: ecs:service:DesiredCount
    MinCapacity: 1
    MaxCapacity: 3
    RoleARN: !GetAtt AutoScalingRole.Arn

ScalingPolicy:
  Type: AWS::ApplicationAutoScaling::ScalingPolicy
  DependsOn: ScalableTarget
  Properties:
    PolicyName: !Sub "${AppName}-${Environment}-scale-policy"
    PolicyType: TargetTrackingScaling
    ScalingTargetId: !Ref ScalableTarget
    TargetTrackingScalingPolicyConfiguration:
      TargetValue: 30.0
      ScaleInCooldown: 120
      ScaleOutCooldown: 60
      PredefinedMetricSpecification:
        PredefinedMetricType: ECSServiceAverageCPUUtilization
